jamiebrynes7/obsidian-todoist-plugin

CHANGELOG.md
README.md
package-lock.json
package.json
src/TaskList.svelte
src/TodoistQuery.svelte
src/api.ts
src/settings.ts

Fixes #13 
Looks roughly like:

Render dates with tasks

---

CHANGELOG.md
src/api.ts

Fix `task-overdue` disappearing

---

CHANGELOG.md
src/TaskList.svelte

Add 'contains-task-list' to `ul` parent 

---

.github/workflows/premerge.yml
.vscode/launch.json
CHANGELOG.md
package-lock.json
package.json
src/api.ts
tests/tasks.ts

Found a bug while writing the tests too!

Add unit tests to task parsing & comparisons

---

README.md

Reference #34 in the readme for unsupported filters.

Reference #34 in the readme

---

CHANGELOG.md
README.md
src/TaskList.svelte
src/api.ts
src/obsidian.d.ts
src/plugin.ts
src/settings.ts
tests/tasks.ts

Render project & section with tasks

---

CHANGELOG.md
README.md
src/TaskList.svelte

This PR satisfies a few feature requests: 
- Fixes #36 
- Fixes #32

Extra date information as CSS classes

---

CHANGELOG.md
README.md
src/TaskList.svelte
src/api.ts
src/settings.ts
tests/tasks.ts

Add label rendering to tasks

---

CHANGELOG.md
src/settings.ts

Fix label rendering

---

CHANGELOG.md
src/api.ts
src/log.ts
src/plugin.ts
src/settings.ts

Add very basic debug logging and instrumented a few calls

Add capability for debug logging

---

CHANGELOG.md
README.md
src/plugin.ts

Attach class to `workspace-leaf` with injected Todoist query

---

CHANGELOG.md
README.md
package-lock.json
src/index.ts
src/settings.ts
src/token_modal.ts
src/utils.ts

Simplifies the setup process to allow smoother onboarding without fiddling around with the file system

Improve setup process

---

CHANGELOG.md
package-lock.json
package.json
src/index.ts
src/ui/TaskList.svelte

Obsidian already adds the name of the plugin to the command in the Ctrl + P menu.

Rename command to remove redundant information

---

CHANGELOG.md
README.md
src/index.ts
src/modals/createTask/CreateTaskModalContent.svelte
src/modals/createTask/createTaskModal.ts
src/modals/enterToken/EnterTokenModalContent.svelte
src/utils.ts

Add command for inserting Obsidian URI into task

---

CHANGELOG.md
src/queryInjector.ts

Fix query injector flakiness

---

CHANGELOG.md
src/ui/TaskList.svelte
src/ui/TaskRenderer.svelte
styles.css

Handle markdown & uncompletable tasks

---

CHANGELOG.md
src/api/models.ts
src/result.ts
src/ui/TodoistQuery.svelte

Add task count templating 

---

CHANGELOG.md
src/contextMenu.ts
src/modals/createTask/CreateTaskModalContent.svelte

Thanks to #146 and @oleeskild for the original implementation!

Create task when pressing enter

---

CHANGELOG.md
package.json
src/index.ts
src/settings.ts
src/token.ts

Support custom obsidian directory

---

CHANGELOG.md
src/ui/TaskRenderer.svelte
test-vault/.gitignore
test-vault/.obsidian/appearance.json

Closes https://github.com/jamiebrynes7/obsidian-todoist-plugin/issues/122

Move priority class to outer div

---

CHANGELOG.md
src/api/api.ts

Use requestUrl instead of fetch

---

CHANGELOG.md
src/index.ts
src/modals/createTask/createTaskModal.ts
src/utils.ts

Fix 'Add Todoist Task' selection in editor pane

---

CHANGELOG.md
src/api/api.ts
src/ui/TaskList.svelte
src/ui/TaskRenderer.svelte
src/utils.ts

Fixes https://github.com/jamiebrynes7/obsidian-todoist-plugin/issues/165

Fix task completion handling

---

CHANGELOG.md
src/api/models.ts
src/ui/TaskRenderer.svelte

Add CSS selector for tasks due today

---

CHANGELOG.md
src/settings.ts
src/ui/TaskRenderer.svelte

Adds a settings toggle and conditional logic to turn task description rendering on/off.
// Resubmitting PR with CHANGELOG, merged against develop branch.

Added toggle render description

---

CHANGELOG.md
src/index.ts
src/modals/createTask/createTaskModal.ts
src/settings.ts

A follow on from #241, this makes the change optional through a setting & adds a changelog entry.

Add option for parenthesis around page links

---

CHANGELOG.md
package.json
src/query/injector.ts
src/query/replacements.test.ts
src/query/replacements.ts

Supersedes #246, added some tests + refactored the impl slightly.

Add filename replacement functionality

---

CHANGELOG.md
README.md
src/query/parser.test.ts
src/query/parser.ts
src/ui/TodoistQuery.svelte

Now that the buttons are floating, we can omit the title entirely if its not provided. Thus we can make it optional completely!

Make title parameter optional

---

src/api/index.ts
src/data/index.ts
src/index.ts
src/ui/ErrorDisplay.svelte
src/ui/QueryErrorDisplay.svelte
src/ui/TodoistQuery.svelte
src/utils.ts
styles.css

A handful of fixes, tweaks, and improvements before releasing v1.12

Misc fixes & tweaks

---

CHANGELOG.md
plugin/src/data/transformations/sorting.test.ts
plugin/src/data/transformations/sorting.ts
plugin/src/query/parser.ts
plugin/src/query/query.ts

fix: correct priorityAscending/Descending order

---

docs/docs/changelog.md
plugin/src/data/index.ts
plugin/src/index.ts
plugin/src/ui/query/QueryRoot.tsx
plugin/src/ui/query/displays/NotReadyDisplay.tsx
plugin/src/ui/query/displays/index.ts

Anecdotally, seeing the plugin take ~20ms to load after these changes. Related to https://github.com/jamiebrynes7/obsidian-todoist-plugin/issues/347

Optimize plugin load time

---

docs/docs/changelog.md
plugin/src/data/dueDate.ts

Related to https://github.com/jamiebrynes7/obsidian-todoist-plugin/issues/371

fix: respect Todoist floating timezones

---

.gitignore
plugin/src/i18n/index.ts
plugin/src/i18n/langs/nl.ts

On your request I've created the Dutch translation.

feat: Adding Dutch translation.
